### ISSUE TITLE
[Epic]: bizzNest Meet Up App

### ISSUE THREAD

**Issue by elimanzo** [BizzNEST/salinas-bizznest-scheduler#14]
## Epic Checklist

- [ ]  Intern Data Management
- [ ]  Randomized Scheduling
- [ ]  Selection and Filtering
- [ ]  Rule Configuration
- [ ]  Manual Override
- [ ]  Edge Case Handling
- [ ]  User Interface
- [ ]  Accessibility

## Additional context
WIP
