### ISSUE TITLE
[Feat]: Create JSON, format, and add intern data

### ISSUE THREAD

**Issue by jacky-p** [BizzNEST/salinas-bizznest-scheduler#17]
## Description
Create a JSON and format with data structure chosen to represent intern data.

### Template for how we plan to organize our JSON object

<img width="519" alt="Screen Shot 2024-09-19 at 11 47 45 AM" src="https://github.com/user-attachments/assets/90b74280-d691-4257-af3f-a9184e1ddb3d">

### Tasks

- [x] create a directory called `documents`
- [x] create `interns.json`
- [x] Got to [Asana](https://app.asana.com/0/1208107952814046/1208107953599543) and manually input all intern data that would be relevant (Bonus: Maybe include data that could be useful for us in the future, like there actual schedule :))

### Additional Resources
[JSON](https://www.w3schools.com/js/js_json.asp)
[How to Create a JSON file](https://codebeautify.org/blog/how-to-create-json-file/)
