### ISSUE TITLE
[Feat]: Add a Responsive Header Component

### ISSUE THREAD

**Issue by elimanzo** [BizzNEST/salinas-bizznest-scheduler#21]
## Description
[Initial Designs](https://www.figma.com/design/1nsYgWIN5bC7NnnVApTcK4/Salinas---bizzNest-Scheduler?node-id=0-1&node-type=canvas&t=TLQ1O5AYgPPOLJtm-0) design

### Web
![image](https://github.com/user-attachments/assets/b30932eb-bd3b-4eca-b5a2-6caa990c6c93)

### Mobile
![image](https://github.com/user-attachments/assets/2bc1e7d5-1b15-4c85-bcb9-993d7e0b7b33)

> \[!NOTE]\
>  Every single UI PR should consist of a Screenshot and/or video (You can use cmd+shift+4 for screenshots and cmd+shift+5 for video recordings) and should be mobile responsive (show the mobile view)

### Tasks

- [x] Create a header with proper semantics tags
- [x] Have the correct background color
- [x] Have the correct font
- [x] Have the Digital Nest Logo (note the logo for mobile is different)
- [x] Have the content properly aligned (keep title center, logo left ... etc)

### Additional Resources + Notes
Good to look into CSS + Semantic Tags + HTML
