### ISSUE TITLE
[Feat]: Add a Responsive Footer

### ISSUE THREAD

**Issue by elimanzo** [BizzNEST/salinas-bizznest-scheduler#22]
## Description
[Initial Designs](https://www.figma.com/design/1nsYgWIN5bC7NnnVApTcK4/Salinas---bizzNest-Scheduler?node-id=0-1&node-type=canvas&t=TLQ1O5AYgPPOLJtm-0) design

### Web
![image](https://github.com/user-attachments/assets/eff8f61a-e445-4d6a-b0dc-3e31caa398d7)

### Mobile
![image](https://github.com/user-attachments/assets/5783d02b-99d3-4e49-851c-246341e94106)

> \[!NOTE]\
>  Every single UI PR should consist of a Screenshot and/or video (You can use cmd+shift+4 for screenshots and cmd+shift+5 for video recordings) and should be mobile responsive (show the mobile view)

### Tasks

- [x] Create a footer with proper semantics tags
- [x] Have the correct background color
- [x] Have the correct font
- [ ] Have the Digital Nest Logo 
- [x] Have the content properly aligned (keep title center)

### Additional Resources + Notes
Good to look into CSS + Semantic Tags + HTML
