### ISSUE TITLE
[Feat]: Add Interns List Card Component

### ISSUE THREAD

**Issue by elimanzo** [BizzNEST/salinas-bizznest-scheduler#23]
## Description
[Initial Designs](https://www.figma.com/design/1nsYgWIN5bC7NnnVApTcK4/Salinas---bizzNest-Scheduler?node-id=0-1&node-type=canvas&t=TLQ1O5AYgPPOLJtm-0) design

### Web
![image](https://github.com/user-attachments/assets/52836ff7-0f37-4573-8026-ed98247bde44)

### Mobile
![image](https://github.com/user-attachments/assets/2e197392-f745-4358-adf5-ccc1a18c4e15)

> \[!NOTE]\
>  Every single UI PR should consist of a Screenshot and/or video (You can use cmd+shift+4 for screenshots and cmd+shift+5 for video recordings) and should be mobile responsive (show the mobile view)

### Tasks

- [ ] Create a container that will hold the interns info
- [ ] Dynamically display the interns info
- [ ] Create check boxes, for each intern
- [ ] Create a buttons to select all + deselect all
- [ ] Add the department pills (the filters will determine what pills are shown)
- [ ] Have the content properly aligned (keep title center)
- [ ] Background / content / margins / paddings should be consistent

### Additional Resources + Notes
Focus on implementing the design ( you can make dummy mock data), then as soon as #17 is done, then we can dynamically display them
