### ISSUE TITLE
[Feat]: Add Department Pill Component

### ISSUE THREAD

**Issue by elimanzo** [BizzNEST/salinas-bizznest-scheduler#24]
## Description
[Initial Designs](https://www.figma.com/design/1nsYgWIN5bC7NnnVApTcK4/Salinas---bizzNest-Scheduler?node-id=0-1&node-type=canvas&t=TLQ1O5AYgPPOLJtm-0) design

![image](https://github.com/user-attachments/assets/edae6a26-75ce-401e-bcdd-2da4123b3157)

> \[!NOTE]\
>  Every single UI PR should consist of a Screenshot and/or video (You can use cmd+shift+4 for screenshots and cmd+shift+5 for video recordings) and should be mobile responsive (show the mobile view)

### Tasks

- [x] Create a list of all the departments
- [x] Create a container for the pill information
- [x] Dynamically display the pills
- [x] Background / content / margins / paddings + any additional styles should be consistent

### Additional Resources + Notes
This will require some JS + HTML + CSS

**Comment by elimanzo** [comment]
closing because of #59
