### ISSUE TITLE
[Feat]: Week Card Component

### ISSUE THREAD

**Issue by elimanzo** [BizzNEST/salinas-bizznest-scheduler#26]
## Description
[Initial Designs](https://www.figma.com/design/1nsYgWIN5bC7NnnVApTcK4/Salinas---bizzNest-Scheduler?node-id=0-1&node-type=canvas&t=TLQ1O5AYgPPOLJtm-0) design

### Web
![image](https://github.com/user-attachments/assets/8fe10469-3d79-4dd2-a84a-84d9555af4e3)

### Mobile
![image](https://github.com/user-attachments/assets/0c175f88-ec79-481e-be55-6bea1c75cd23)

Card should be collapsible 

![image](https://github.com/user-attachments/assets/35e2bd25-baf4-4593-a4cb-39d80ec70b81)

> \[!NOTE]\
>  Every single UI PR should consist of a Screenshot and/or video (You can use cmd+shift+4 for screenshots and cmd+shift+5 for video recordings) and should be mobile responsive (show the mobile view)

### Tasks

- [x] Create a container that will hold the weekly meeting
- [x] Dynamically display the group interns info (This should show the filtered info)
- [x] Display the department pills
- [x] Add Ice Breaker questions (This can be the same questions for now until we make another json for them)
- [x] Make sure the card is a collapsible
- [x] Background / content / margins / paddings / + other general styles should be consistent

### Additional Resources + Notes
Focus on implementing the design ( you can make dummy mock data), then as soon as #17 is done, then we can dynamically display them.

**Comment by elimanzo** [comment]
I will handle this task

**Comment by elimanzo** [comment]
Closing because of #43
