### ISSUE TITLE
[Feat]: Add Filters + Generate Schedule Component

### ISSUE THREAD

**Issue by elimanzo** [BizzNEST/salinas-bizznest-scheduler#27]
## Description
[Initial Designs](https://www.figma.com/design/1nsYgWIN5bC7NnnVApTcK4/Salinas---bizzNest-Scheduler?node-id=0-1&node-type=canvas&t=TLQ1O5AYgPPOLJtm-0) design

### Web
![image](https://github.com/user-attachments/assets/646c10b7-be9b-42b1-b8ad-17860c2ab95a)

### Mobile
![image](https://github.com/user-attachments/assets/9352da83-18d3-4ad9-8f5b-671485c3de3d)

> \[!NOTE]\
>  Every single UI PR should consist of a Screenshot and/or video (You can use cmd+shift+4 for screenshots and cmd+shift+5 for video recordings) and should be mobile responsive (show the mobile view)

### Tasks

- [x] Create a container that will hold the the filters and the generate schedule button
- [x] Create component for the filters + button 
- [x] The filters should be collapsible
- [x] The collapsible filters should also include check marks (per location + department)
- [x] Make sure that this component stickies to the top as you're scrolling
- [x] Implement mobile side scrolling (This might require a bit tricky CSS) 
- [x] Styles should be consistent to design

### Additional Resources + Notes
Focus on implementing the design, for the interaction of the filters / buttons, we will focus that logic in JS for another task
